### ISSUE TITLE
Uncaught TypeError: Cannot read property 'termSetFont' of undefined

### ISSUE THREAD

**Issue by wzowee** [nitrous-io/nitrogen-dist#17]
[Enter steps to reproduce below:]
1. Tried to open the shell in Atom.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.3
**Thrown From**: [nitrogen](https://github.com/nitrous-io/nitrogen-dist) package, v0.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'termSetFont' of undefined

```
At /Users/REMOVED/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1

TypeError: Cannot read property 'termSetFont' of undefined
    at t.setFont (/Users/REMOVED/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1:2858)
    at t._createClass.value (/Users/REMOVED/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1:5121)
    at EventEmitter.n (/Users/REMOVED/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1:4654)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -5:53.3.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".unison",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "*~"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "nitrogen": {
    "showWelcomeOnStartup": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.13
language-haml, v0.23.14
linter, v1.11.3
linter-jsonlint, v1.1.4
linter-ruby, v1.2.1
nitrogen, v0.1.4
react, v0.12.10
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by styner32** [comment]
This should be fixed in v0.1.5. Do you still have the issue?

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
