### ISSUE TITLE
Failed to load the nitrogen package

### ISSUE THREAD

**Issue by harryspink** [nitrous-io/nitrogen-dist#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.2
**Thrown From**: [nitrogen](https://github.com/nitrous-io/nitrogen-dist) package, v0.1.2
### Stack Trace

Failed to load the nitrogen package

```
At Cannot redefine property: PATH

TypeError: Cannot redefine property: PATH
    at Function.defineProperty (native)
    at fn (/Users/username/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:152:27)
    at metaToValue (/Users/username/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:168:11)
    at process.Object.defineProperty.get [as env] (/Users/username/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:161:24)
    at Object.module.exports.getEnv (/Users/username/.atom/packages/nitrogen/lib/util/iwc.js:1:933)
    at new e (/Users/username/.atom/packages/nitrogen/lib/stores/nsync-store.js:1:1859)
    at Object.<anonymous> (/Users/username/.atom/packages/nitrogen/lib/stores/nsync-store.js:1:2752)
    at Module._compile (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/username/.atom/packages/nitrogen/lib/nitrogen.js:1:1442)
    at Module._compile (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at /Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:682:21)
    at module.exports (/Users/username/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Users/username/Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Users/username/Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.13
nitrogen, v0.1.2
remote-edit, v1.8.22

# Dev
No dev packages
```

**Comment by styner32** [comment]
Hi @harryspink. Could you share more information to reproduce? When does this happen and does it happen every time or randomly?

**Comment by harryspink** [comment]
The error first appears after the plugin is installed and then every time I use Atom. Removing the Nitrogen plugin stops the pop up. The error renders the plugin unusable.

<img width="494" alt="screen shot 2016-01-12 at 10 16 39" src="https://cloud.githubusercontent.com/assets/3799258/12260956/14be75ba-b916-11e5-9411-57d60b98a8cb.png">

**Comment by petejkim** [comment]
May I know what other plugins you may be using?

**Comment by styner32** [comment]
Hi @harryspink. Could you share your env variables with our plugin installed?

You can View -> Developer -> Toggle Developer Tools and run `require('remote').getGlobal('process').env` in the console.
Then you can take a screenshot with the result. ( please expand `> Object {}` before do this. So we can see what values you have)

**Comment by barovski** [comment]
Same issue for me
Cannot redefine property: PATH
Hide Stack Trace
TypeError: Cannot redefine property: PATH
    at Function.defineProperty (native)
    at fn (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:152:27)
    at metaToValue (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:168:11)
    at process.Object.defineProperty.get [as env](/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:161:24)
    at Object.module.exports.getEnv (/Users/Owner/.atom/packages/nitrogen/lib/util/iwc.js:1:1057)
    at new e (/Users/Owner/.atom/packages/nitrogen/lib/stores/nsync-store.js:1:1910)
    at Object.<anonymous> (/Users/Owner/.atom/packages/nitrogen/lib/stores/nsync-store.js:1:3100)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Owner/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1:2056)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Owner/.atom/packages/nitrogen/lib/elements/nitrogen-shell-element.js:1:1248)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Owner/.atom/packages/nitrogen/lib/shell.js:1:620)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
