### ISSUE TITLE
Uncaught TypeError: Cannot read property 'termStart' of undefined

### ISSUE THREAD

**Issue by pratyushsharma** [nitrous-io/nitrogen-dist#23]
[Enter steps to reproduce below:]
1. Started a new shell

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [nitrogen](https://github.com/nitrous-io/nitrogen-dist) package, v0.1.5
### Stack Trace

Uncaught TypeError: Cannot read property 'termStart' of undefined

```
At /Users/bhawnasharma/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1

TypeError: Cannot read property 'termStart' of undefined
    at t._createClass.value (/Users/bhawnasharma/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1:5207)
    at EventEmitter.i (/Users/bhawnasharma/.atom/packages/nitrogen/lib/components/nitrogen-shell.js:1:4729)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".unison",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "*~"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "nitrogen": {
    "showWelcomeOnStartup": false
  }
}
```
### Installed Packages

``` coffee
# User
jslint, v1.5.1
nitrogen, v0.1.5

# Dev
No dev packages
```

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

## Links:

[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
