### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by garthgoldwater** [nitrous-io/nitrogen-dist#24]
this popped up as nitrogen was trying to log in to nitrous. listed line number as `nitrogen/node_modules/react/lib/ReactCompositeComponent.js:559`. 

stack trace:
`TypeError: Cannot read property '_currentElement' of null
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:559:52)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.ReactReconciler.receiveComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.ReactChildReconciler.updateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:351:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:326:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.ReactReconciler.receiveComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.ReactChildReconciler.updateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:351:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:326:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.ReactReconciler.receiveComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:87:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:421:12)
    at Object.ReactReconciler.performUpdateIfNecessary (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:102:22)
    at runBatchedUpdates (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:129:21)
    at ReactReconcileTransaction.Mixin.perform (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:147:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:149:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.enqueueUpdate (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:176:22)
    at enqueueUpdate (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdateQueue.js:24:16)
    at Object.ReactUpdateQueue.enqueueSetState (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdateQueue.js:190:5)
    at t.ReactComponent.setState (/Users/garth/.atom/packages/nitrogen/node_modules/react/lib/ReactComponent.js:65:16)
    at nitrogen-toolbar._createClass.value (/Users/garth/.atom/packages/nitrogen/lib/elements/nitrogen-toolbar-element.js:1:2869)
    at emitNone (events.js:72:20)
    at t.emit (events.js:166:7)
    at t._createClass.value (/Users/garth/.atom/packages/nitrogen/lib/stores/store.js:1:2244)
    at /Users/garth/.atom/packages/nitrogen/lib/stores/container-store.js:1:3025
    at EventEmitter.<anonymous> (/Users/garth/.atom/packages/nitrogen/lib/stores/container-store.js:1:3040)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)`

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
