### ISSUE TITLE
Uncaught TypeError: n.termWrite is not a function

### ISSUE THREAD

**Issue by MCBama** [nitrous-io/nitrogen-dist#31]
[Enter steps to reproduce below:]
1. Right click on shell window
2. Select "Split Right"

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [nitrogen](https://github.com/nitrous-io/nitrogen-dist) package, v0.1.5
### Stack Trace

Uncaught TypeError: n.termWrite is not a function

```
At C:\Users\mclev\.atom\packages\nitrogen\lib\components\nitrogen-shell.js:1

TypeError: n.termWrite is not a function
    at Socket.<anonymous> (C:\Users\mclev\.atom\packages\nitrogen\lib\components\nitrogen-shell.js:1:5908)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
     -3:27.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:34.7.0 nitrogen:show-login-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:26.6.0 editor:select-to-first-character-of-line (atom-text-editor.secure-text-field.editor.mini.is-focused)
     -1:24.7.0 core:confirm (atom-text-editor.secure-text-field.editor.mini.is-focused)
  2x -0:45.5.0 tree-view:toggle-focus (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.1.0 tabs:split-right (li.tab.sortable.active.right-clicked)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".unison",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "*~"
    ]
  },
  "nitrogen": {
    "showWelcomeOnStartup": false
  }
}
```
### Installed Packages

``` coffee
# User
nitrogen, v0.1.5

# Dev
No dev packages
```

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by styner32** [comment]
We've released v0.1.6 with the fix. Could you try again?

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
