### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isRunning' of undefined

### ISSUE THREAD

**Issue by mattmortek** [nitrous-io/nitrogen-dist#34]
`/home/proton/.atom/packages/nitrogen/lib/components/nitrogen-container-toolbar.js:1
Hide Stack Trace
TypeError: Cannot read property 'isRunning' of undefined
    at t._createClass.value (/home/proton/.atom/packages/nitrogen/lib/components/nitrogen-container-toolbar.js:1:6177)
    at t._createClass.value (/home/proton/.atom/packages/nitrogen/lib/components/nitrogen-container-toolbar.js:1:7947)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:560:36)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.ReactReconciler.receiveComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.ReactChildReconciler.updateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:351:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:326:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.ReactReconciler.receiveComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.ReactChildReconciler.updateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:351:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactMultiChild.js:326:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.ReactReconciler.receiveComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:87:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactCompositeComponent.js:421:12)
    at Object.ReactReconciler.performUpdateIfNecessary (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactReconciler.js:102:22)
    at runBatchedUpdates (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:129:21)
    at ReactReconcileTransaction.Mixin.perform (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:147:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:149:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.enqueueUpdate (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:176:22)
    at enqueueUpdate (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdateQueue.js:24:16)
    at Object.ReactUpdateQueue.enqueueSetState (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdateQueue.js:190:5)
    at t.ReactComponent.setState (/home/proton/.atom/packages/nitrogen/node_modules/react/lib/ReactComponent.js:65:16)
    at t.findContainer (/home/proton/.atom/packages/nitrogen/lib/components/nitrogen-toolbar.js:1:2339)
    at t.containerStoreDidChange (/home/proton/.atom/packages/nitrogen/lib/components/nitrogen-toolbar.js:1:2209)
    at emitNone (events.js:72:20)
    at t.emit (events.js:166:7)
    at t._createClass.value (/home/proton/.atom/packages/nitrogen/lib/stores/store.js:1:2244)
    at EventEmitter.<anonymous> (/home/proton/.atom/packages/nitrogen/lib/stores/container-store.js:1:2327)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.ipcRenderer.emit (/usr/share/atom-beta/resources/atom.asar/renderer/api/lib/ipc.js:16:12)`

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by styner32** [comment]
We've released v0.1.6 with the fix. Could you try again?

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by mattmortek** [comment]
@styner32 It didn't help. 

One hint, maybe it will help you - it happens only with shared with me machine. In case of my own machines, it doesn't show.

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by styner32** [comment]
Oh thank you for the hint. We will look into that

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by styner32** [comment]
We've released new version with the fix. Could you try again?

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by mattmortek** [comment]
Yes, it fixed the problem.

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
