### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slug' of undefined

### ISSUE THREAD

**Issue by matthiasludwig** [nitrous-io/nitrogen-dist#35]
[Enter steps to reproduce below:]
1. Righ after starting Atom unable to "Start Workstation"

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [nitrogen](https://github.com/nitrous-io/nitrogen-dist) package, v0.1.9
### Stack Trace

Uncaught TypeError: Cannot read property 'slug' of undefined

```
At /Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactErrorUtils.js:53

TypeError: Cannot read property 'slug' of undefined
    at e._createClass.value (/Users/.../.atom/packages/nitrogen/lib/actions/host-actions.js:1:1214)
    at t.startHost (/Users/.../.atom/packages/nitrogen/lib/components/nitrogen-container-toolbar.js:1:4685)
    at Object.invokeGuardedCallback (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.EventPluginHub.processEventQueue (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:94:20)
    at ReactEventListener.dispatchEvent (/Users/.../.atom/packages/nitrogen/node_modules/react/lib/ReactEventListener.js:204:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".unison",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "*~"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "nitrogen": {
    "showWelcomeOnStartup": false
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
merge-conflicts, v1.4.3
minimap, v4.24.3
nitrogen, v0.1.9
pigments, v0.29.1

# Dev
No dev packages
```

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --


Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

Links:
------
[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by styner32** [comment]
Thanks for the report. We've fixed in new release. Could you update and check again?

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

## Links:

[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq

**Comment by matthiasludwig** [comment]
So far it works again! Thank you!

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

## Links:

[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
