### ISSUE TITLE
Uncaught TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by kpnolan** [nitrous-io/nitrogen-dist#39]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [nitrogen](https://github.com/nitrous-io/nitrogen-dist) package, v0.1.10
### Stack Trace

Uncaught TypeError: Cannot read property 'state' of undefined

```
At /Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactErrorUtils.js:53

TypeError: Cannot read property 'state' of undefined
    at t.hostStoreDidChange (/Users/kpnolan/.atom/packages/nitrogen/lib/components/nitrogen-container-toolbar.js:1:3411)
    at emitNone (events.js:72:20)
    at t.emit (events.js:166:7)
    at t._createClass.value (/Users/kpnolan/.atom/packages/nitrogen/lib/stores/store.js:1:2244)
    at t._createClass.value (/Users/kpnolan/.atom/packages/nitrogen/lib/stores/host-store.js:1:2634)
    at Object.ID_1 (/Users/kpnolan/.atom/packages/nitrogen/lib/stores/store.js:1:1877)
    at e._invokeCallback (/Users/kpnolan/.atom/packages/nitrogen/node_modules/flux/lib/Dispatcher.js:198:24)
    at e.dispatch (/Users/kpnolan/.atom/packages/nitrogen/node_modules/flux/lib/Dispatcher.js:174:14)
    at e._createClass.value (/Users/kpnolan/.atom/packages/nitrogen/lib/actions/token-actions.js:1:1742)
    at handleClickLogout (/Users/kpnolan/.atom/packages/nitrogen/lib/components/nitrogen-account-menu.js:1:2563)
    at handleSelect (/Users/kpnolan/.atom/packages/nitrogen/lib/components/nitrogen-dropdown-menu-item.js:1:1679)
    at Object.invokeGuardedCallback (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.EventPluginHub.processEventQueue (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactUpdates.js:94:20)
    at ReactEventListener.dispatchEvent (/Users/kpnolan/.atom/packages/nitrogen/node_modules/react/lib/ReactEventListener.js:204:20)
```
### Commands

```
  3x -2:56.5.0 tree-view:toggle-focus (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".unison",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "*~"
    ]
  },
  "nitrogen": {
    "showWelcomeOnStartup": false
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.15.0
atomic-chrome, v0.3.0
nitrogen, v0.1.10

# Dev
No dev packages
```

**Comment by nitrogen-ide** [comment]
-- Please reply above this line --

Hello,

We received your Nitrous support request! One of our support engineers
will respond to you as soon as possible. In the meantime, some of
these documents might be helpful: 

https://community.nitrous.io/docs [1]
https://community.nitrous.io/docs/problems-previewing-my-app [2]
https://community.nitrous.io/docs/ide-overview [3]
https://community.nitrous.io/docs/billing-pricing-faq [4]

Thanks!

Nitrous Support

## Links:

[1] https://community.nitrous.io/docs
[2] https://community.nitrous.io/docs/problems-previewing-my-app
[3] https://community.nitrous.io/docs/ide-overview
[4] https://community.nitrous.io/docs/billing-pricing-faq
